// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260306214539_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("dotnet_store.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            Fiyat = 40000.0,
                            UrunAdi = "Samsung Galaxy S20"
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            Fiyat = 50000.0,
                            UrunAdi = "Samsung Galaxy S21"
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            Fiyat = 60000.0,
                            UrunAdi = "Samsung Galaxy S22"
                        },
                        new
                        {
                            Id = 4,
                            Aktif = true,
                            Fiyat = 70000.0,
                            UrunAdi = "Samsung Galaxy S23"
                        },
                        new
                        {
                            Id = 5,
                            Aktif = true,
                            Fiyat = 80000.0,
                            UrunAdi = "Samsung Galaxy S24"
                        },
                        new
                        {
                            Id = 6,
                            Aktif = true,
                            Fiyat = 90000.0,
                            UrunAdi = "Samsung Galaxy S25"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
