// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260621061129_UpdateOrder")]
    partial class UpdateOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("dotnet_store.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("dotnet_store.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("dotnet_store.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CartId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("dotnet_store.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("UrunId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("dotnet_store.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriAdi = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 2,
                            KategoriAdi = "Beyaz Eşya",
                            Url = "beyaz-esya"
                        },
                        new
                        {
                            Id = 3,
                            KategoriAdi = "Giyim",
                            Url = "giyim"
                        },
                        new
                        {
                            Id = 4,
                            KategoriAdi = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 5,
                            KategoriAdi = "Kozmetik",
                            Url = "kozmetik"
                        },
                        new
                        {
                            Id = 6,
                            KategoriAdi = "Kitap",
                            Url = "kitap"
                        },
                        new
                        {
                            Id = 7,
                            KategoriAdi = "Kategori 1",
                            Url = "kategori-1"
                        },
                        new
                        {
                            Id = 8,
                            KategoriAdi = "Kategori 2",
                            Url = "kategori-2"
                        },
                        new
                        {
                            Id = 9,
                            KategoriAdi = "Kategori 3",
                            Url = "kategori-3"
                        },
                        new
                        {
                            Id = 10,
                            KategoriAdi = "Kategori 4",
                            Url = "kategori-4"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdresSatiri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostaKodu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiparisNotu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ToplamFiyat")
                        .HasColumnType("REAL");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("dotnet_store.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UrunId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("dotnet_store.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SliderImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "slider1 aciklama",
                            Aktif = true,
                            Baslik = "slider1",
                            ImageUrl = "slider-1.jpeg",
                            Index = 0
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "slider2 aciklama",
                            Aktif = true,
                            Baslik = "slider2",
                            ImageUrl = "slider-2.jpeg",
                            Index = 1
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "slider3 aciklama",
                            Aktif = true,
                            Baslik = "slider3",
                            ImageUrl = "slider-3.jpeg",
                            Index = 2
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anasayfa")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resim")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eligendi cumque iste magni, deleniti ipsa esse quae nesciunt quod autem maxime minus facere mollitia ullam corporis similique magnam enim dolorem alias.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 40000.0,
                            KategoriId = 1,
                            Resim = "1.jpeg",
                            UrunAdi = "Samsung Galaxy S20"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eligendi cumque iste magni, deleniti ipsa esse quae nesciunt quod autem maxime minus facere mollitia ullam corporis similique magnam enim dolorem alias.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 50000.0,
                            KategoriId = 2,
                            Resim = "2.jpeg",
                            UrunAdi = "Samsung Galaxy S21"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eligendi cumque iste magni, deleniti ipsa esse quae nesciunt quod autem maxime minus facere mollitia ullam corporis similique magnam enim dolorem alias.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 60000.0,
                            KategoriId = 2,
                            Resim = "3.jpeg",
                            UrunAdi = "Samsung Galaxy S22"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eligendi cumque iste magni, deleniti ipsa esse quae nesciunt quod autem maxime minus facere mollitia ullam corporis similique magnam enim dolorem alias.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 70000.0,
                            KategoriId = 3,
                            Resim = "4.jpeg",
                            UrunAdi = "Samsung Galaxy S23"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eligendi cumque iste magni, deleniti ipsa esse quae nesciunt quod autem maxime minus facere mollitia ullam corporis similique magnam enim dolorem alias.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 80000.0,
                            KategoriId = 3,
                            Resim = "5.jpeg",
                            UrunAdi = "Samsung Galaxy S24"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eligendi cumque iste magni, deleniti ipsa esse quae nesciunt quod autem maxime minus facere mollitia ullam corporis similique magnam enim dolorem alias.",
                            Aktif = false,
                            Anasayfa = true,
                            Fiyat = 90000.0,
                            KategoriId = 4,
                            Resim = "6.jpeg",
                            UrunAdi = "Samsung Galaxy S25"
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eligendi cumque iste magni, deleniti ipsa esse quae nesciunt quod autem maxime minus facere mollitia ullam corporis similique magnam enim dolorem alias.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 100000.0,
                            KategoriId = 4,
                            Resim = "7.jpeg",
                            UrunAdi = "Samsung Galaxy S26"
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eligendi cumque iste magni, deleniti ipsa esse quae nesciunt quod autem maxime minus facere mollitia ullam corporis similique magnam enim dolorem alias.",
                            Aktif = false,
                            Anasayfa = true,
                            Fiyat = 110000.0,
                            KategoriId = 1,
                            Resim = "8.jpeg",
                            UrunAdi = "Samsung Galaxy S27"
                        },
                        new
                        {
                            Id = 9,
                            Aciklama = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eligendi cumque iste magni, deleniti ipsa esse quae nesciunt quod autem maxime minus facere mollitia ullam corporis similique magnam enim dolorem alias.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 1000.0,
                            KategoriId = 6,
                            Resim = "9.jpeg",
                            UrunAdi = "Beyninizin Duygusal hayatı"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_store.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dotnet_store.Models.CartItem", b =>
                {
                    b.HasOne("dotnet_store.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_store.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("dotnet_store.Models.OrderItem", b =>
                {
                    b.HasOne("dotnet_store.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_store.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("dotnet_store.Models.Urun", b =>
                {
                    b.HasOne("dotnet_store.Models.Kategori", "Kategori")
                        .WithMany("Uruns")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("dotnet_store.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("dotnet_store.Models.Kategori", b =>
                {
                    b.Navigation("Uruns");
                });

            modelBuilder.Entity("dotnet_store.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
